version: "3"
services:
  broker:
    container_name: rabbitMQBroker
    image: "rabbitmq:3.8-management"
    ports:
    - "15672:15672"
    - "5672:5672"

  simulator:
    image: "rabbitmqsimulator:latest"
    build:
      context: .
      dockerfile: Dockerfile-simulator
    ports:
    - "3000:3000"

